name: Build API documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dart Sass
        run: |
          npm install -g sass
          sass --version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.167.0'
          extended: true

      - name: Verify Environment
        run: |
          hugo env
          which sass
          sass --version

      - name: Install dependencies
        run: |
          npm install
          hugo mod tidy
          hugo mod npm pack
          npm install

      - name: Build
        run: hugo

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public